# Build
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t reverseproxy ./reverseproxy
# Do similar for other three images

# Tagging
- docker tag udagram-api-user shivanand3939/udagram-api-user:v1
- docker tag udagram-api-feed shivanand3939/udagram-api-feed:v1
- docker tag udagram-frontend shivanand3939/udagram-frontend:v1
- docker tag reverseproxy shivanand3939/reverseproxy:v1
# Do similar for other three images


- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push shivanand3939/udagram-api-user:v1
- docker push shivanand3939/udagram-api-feed:v1
- docker push shivanand3939/udagram-frontend:v1
- docker push shivanand3939/reverseproxy:v1
# Do similar for other three images
